use crate::model::LensOutputBlock;
use agent_client_protocol::{
    schema::v1::{
        ContentBlock, ContentChunk, EmbeddedResourceResource, SessionUpdate, ToolCallContent,
        ToolCallId, ToolCallStatus,
    },
    Error,
};
use base64::prelude::*;

const MAX_INLINE_IMAGE_DECODED_BYTES: usize = 10 * 1024 * 1024;
const MAX_INLINE_IMAGE_ENCODED_BYTES: usize = MAX_INLINE_IMAGE_DECODED_BYTES.div_ceil(3) * 4;
const MAX_TOOL_CALLS: usize = 256;
const MAX_TOOL_MEDIA_BLOCKS: usize = 32;
const MAX_TOOL_IMAGE_ENCODED_BYTES: usize = 64 * 1024 * 1024;
const MAX_HTML_BYTES: usize = 512 * 1024;
// The message path has no per-tool budget to inherit, so it carries its own. Chunks are
// agent-supplied deltas over an unframed stdio stream, and the whole snapshot is cloned
// and broadcast on every update, so unbounded growth here is quadratic as well as large.
const MAX_MESSAGE_BLOCKS: usize = 512;
const MAX_MESSAGE_TEXT_BYTES: usize = 8 * 1024 * 1024;
const MAX_MESSAGE_IMAGE_ENCODED_BYTES: usize = 64 * 1024 * 1024;

/// Message-entry totals measured against the per-turn message budget. Named so the three
/// counts cannot be bound in the wrong order at a call site.
#[derive(Debug, Default)]
struct MessageTotals {
    blocks: usize,
    text_bytes: usize,
    image_bytes: usize,
}

/// One prompt turn owns the ordered message segments and tool-result snapshots.
/// Tool updates replace their content at the first notification's position.
#[derive(Debug, Default)]
pub(crate) struct AgentOutputCandidate {
    entries: Vec<OutputEntry>,
    progress: ProgressText,
    pub(crate) received_updates: usize,
}

/// ACP chunks are deltas, not complete messages. Retain only a bounded latest paragraph.
#[derive(Debug, Default)]
struct ProgressText {
    identity: Option<(bool, Option<String>)>,
    text: String,
}

impl ProgressText {
    fn record(&mut self, chunk: &ContentChunk, thought: bool) {
        let ContentBlock::Text(content) = &chunk.content else {
            return;
        };
        if content.text.is_empty() {
            return;
        }
        let identity = (thought, chunk.message_id.as_ref().map(ToString::to_string));
        if self.identity.as_ref() != Some(&identity) {
            self.text.clear();
            self.identity = Some(identity);
        }
        self.text.push_str(&content.text);
        // Keep the latest non-empty line; blank trailing separators do not erase progress.
        let trimmed = self.text.trim_end_matches(['\r', '\n']);
        let start = trimmed.rfind(['\r', '\n']).map_or(0, |i| i + 1);
        let tail = &self.text[start..];
        let bounded = tail.char_indices().rev().nth(511).map_or(0, |(i, _)| i);
        self.text = tail[bounded..].to_owned();
    }
}

#[derive(Debug)]
enum OutputEntry {
    Message(Vec<LensOutputBlock>),
    Tool(ToolOutput),
}

#[derive(Debug)]
struct ToolOutput {
    id: ToolCallId,
    status: ToolCallStatus,
    media: Vec<LensOutputBlock>,
}

impl ToolOutput {
    fn visible_media(&self) -> &[LensOutputBlock] {
        if self.status == ToolCallStatus::Completed {
            &self.media
        } else {
            &[]
        }
    }
}

impl AgentOutputCandidate {
    /// Admit the owned publisher only after its turn is sealed. ACP raw fields
    /// remain diagnostics; receipt identity is generated by the HTTP host.
    pub(crate) fn accept_published_html(
        &mut self,
        publication: adapter_output_mcp::PublishedHtml,
    ) -> Result<(), Error> {
        if publication.html.trim().is_empty()
            || publication.html.len() > MAX_HTML_BYTES
            || self.retained_html_count(None) != 0
        {
            return Err(Error::invalid_params().data("Invalid or duplicate HTML publication"));
        }
        self.entries
            .push(OutputEntry::Message(vec![LensOutputBlock::Html {
                message_id: None,
                resource_id: publication.id.to_string(),
                mime_type: "text/html".into(),
                uri: format!("urn:lens:html:{}", publication.id),
                byte_length: publication.html.len(),
                text: publication.html,
            }]));
        Ok(())
    }

    /// Returns whether the displayable content changed. Protocol-only updates
    /// still advance the received-update count without becoming Interpretation.
    pub(crate) fn record_update(
        &mut self,
        update: SessionUpdate,
        safe_mode_id: &str,
    ) -> Result<bool, Error> {
        self.received_updates = self.received_updates.checked_add(1).ok_or_else(|| {
            Error::internal_error().data("Agent update count exceeded the finite local limit")
        })?;
        match &update {
            SessionUpdate::AgentMessageChunk(chunk) => self.progress.record(chunk, false),
            SessionUpdate::AgentThoughtChunk(chunk) => self.progress.record(chunk, true),
            SessionUpdate::ToolCall(_) | SessionUpdate::ToolCallUpdate(_) => {
                self.progress.identity = None;
            }
            _ => {}
        }
        match update {
            SessionUpdate::AgentMessageChunk(chunk) => {
                let mut block = lens_output_block(chunk);
                enforce_html_limit(&mut block, || self.retained_html_count(None));
                if matches!(&block, LensOutputBlock::Markdown { text, .. } if text.is_empty()) {
                    return Ok(false);
                }
                let totals = self.message_totals();
                let added = std::slice::from_ref(&block);
                if totals.blocks >= MAX_MESSAGE_BLOCKS
                    || totals.text_bytes + message_text_bytes(added) > MAX_MESSAGE_TEXT_BYTES
                    || totals.image_bytes + encoded_image_bytes(added)
                        > MAX_MESSAGE_IMAGE_ENCODED_BYTES
                {
                    return Err(Error::invalid_params()
                        .data("Agent message output exceeded the per-turn limit"));
                }
                if let Some(OutputEntry::Message(blocks)) = self.entries.last_mut() {
                    push_output_block(blocks, block);
                } else {
                    self.entries.push(OutputEntry::Message(vec![block]));
                }
                Ok(true)
            }
            SessionUpdate::ToolCall(call) => {
                self.update_tool(call.tool_call_id, Some(call.status), Some(call.content))
            }
            SessionUpdate::ToolCallUpdate(update) => self.update_tool(
                update.tool_call_id,
                update.fields.status,
                update.fields.content,
            ),
            SessionUpdate::CurrentModeUpdate(update)
                if update.current_mode_id.to_string() != safe_mode_id =>
            {
                Err(Error::invalid_params().data(format!(
                    "ACP session left required safe mode {safe_mode_id}; refusing to continue"
                )))
            }
            _ => Ok(false),
        }
    }

    fn update_tool(
        &mut self,
        id: ToolCallId,
        status: Option<ToolCallStatus>,
        content: Option<Vec<ToolCallContent>>,
    ) -> Result<bool, Error> {
        // Keep only typed images and explicitly HTML resources. Other tool
        // resources remain private diagnostics, not Interpretation output. Never dereference URIs
        // or inspect rawOutput, tool arguments, diffs, or terminal output.
        let existing = self
            .entries
            .iter()
            .position(|entry| matches!(entry, OutputEntry::Tool(tool) if tool.id == id));
        let mut html_count = self.retained_html_count(existing);
        let media = content.map(|content| {
            content
                .into_iter()
                .filter_map(|content| match content {
                    ToolCallContent::Content(content) if is_tool_media(&content.content) => {
                        let mut block = lens_output_block(ContentChunk::new(content.content));
                        enforce_html_limit(&mut block, || html_count);
                        if let (
                            Some(index),
                            LensOutputBlock::Html {
                                resource_id,
                                text,
                                uri,
                                ..
                            },
                        ) = (existing, &mut block)
                        {
                            if let OutputEntry::Tool(tool) = &self.entries[index] {
                                if let Some(previous_id) =
                                    tool.media.iter().find_map(|previous| match previous {
                                        LensOutputBlock::Html {
                                            resource_id,
                                            text: previous_text,
                                            uri: previous_uri,
                                            ..
                                        } if previous_text == text && previous_uri == uri => {
                                            Some(resource_id)
                                        }
                                        _ => None,
                                    })
                                {
                                    resource_id.clone_from(previous_id);
                                }
                            }
                        }
                        html_count += usize::from(matches!(block, LensOutputBlock::Html { .. }));
                        Some(block)
                    }
                    _ => None,
                })
                .collect::<Vec<_>>()
        });
        let mut tool_count = 0;
        let mut media_count = 0;
        let mut image_bytes = 0;
        for (index, entry) in self.entries.iter().enumerate() {
            if let OutputEntry::Tool(tool) = entry {
                tool_count += 1;
                if Some(index) != existing || media.is_none() {
                    media_count += tool.media.len();
                    image_bytes += encoded_image_bytes(&tool.media);
                }
            }
        }
        if let Some(images) = &media {
            media_count += images.len();
            image_bytes += encoded_image_bytes(images);
        }
        if (existing.is_none() && tool_count >= MAX_TOOL_CALLS)
            || media_count > MAX_TOOL_MEDIA_BLOCKS
            || image_bytes > MAX_TOOL_IMAGE_ENCODED_BYTES
        {
            return Err(
                Error::invalid_params().data("Agent tool output exceeded the per-turn limit")
            );
        }

        if let Some(index) = existing {
            let OutputEntry::Tool(tool) = &mut self.entries[index] else {
                unreachable!("tool position was selected above")
            };
            let next_status = status.unwrap_or(tool.status);
            let next_visible = if next_status == ToolCallStatus::Completed {
                media.as_deref().unwrap_or(&tool.media)
            } else {
                &[]
            };
            let changed = tool.visible_media() != next_visible;
            tool.status = next_status;
            if let Some(images) = media {
                // Omitted content preserves the snapshot; an explicit empty
                // collection clears it, as required by ACP ToolCallUpdate.
                tool.media = images;
            }
            if tool.status == ToolCallStatus::Failed {
                // Failed tools cannot publish HTML, so release its bounded slot.
                tool.media
                    .retain(|block| !matches!(block, LensOutputBlock::Html { .. }));
            }
            Ok(changed)
        } else {
            let mut tool = ToolOutput {
                id,
                status: status.unwrap_or_default(),
                media: media.unwrap_or_default(),
            };
            if tool.status == ToolCallStatus::Failed {
                tool.media
                    .retain(|block| !matches!(block, LensOutputBlock::Html { .. }));
            }
            let changed = !tool.visible_media().is_empty();
            self.entries.push(OutputEntry::Tool(tool));
            Ok(changed)
        }
    }

    pub(crate) fn progress_text(&self) -> Option<String> {
        let text = self.progress.text.trim();
        (!text.is_empty()).then(|| text.to_owned())
    }

    pub(crate) fn blocks(&self) -> Vec<LensOutputBlock> {
        let mut blocks = Vec::new();
        for entry in &self.entries {
            let content = match entry {
                OutputEntry::Message(content) => content,
                OutputEntry::Tool(tool) => tool.visible_media(),
            };
            for block in content {
                push_output_block(&mut blocks, block.clone());
            }
        }
        blocks
    }

    pub(crate) fn has_output(&self) -> bool {
        self.entries.iter().any(|entry| match entry {
            OutputEntry::Message(blocks) => blocks.iter().any(|block| match block {
                LensOutputBlock::Markdown { text, .. } => !text.trim().is_empty(),
                LensOutputBlock::Image { .. }
                | LensOutputBlock::Html { .. }
                | LensOutputBlock::Unsupported { .. } => true,
            }),
            OutputEntry::Tool(tool) => !tool.visible_media().is_empty(),
        })
    }

    /// What message entries already hold, against the per-turn message budget.
    fn message_totals(&self) -> MessageTotals {
        self.entries
            .iter()
            .filter_map(|entry| match entry {
                OutputEntry::Message(blocks) => Some(blocks.as_slice()),
                OutputEntry::Tool(_) => None,
            })
            .fold(MessageTotals::default(), |totals, blocks| MessageTotals {
                blocks: totals.blocks + blocks.len(),
                text_bytes: totals.text_bytes + message_text_bytes(blocks),
                image_bytes: totals.image_bytes + encoded_image_bytes(blocks),
            })
    }

    fn retained_html_count(&self, exclude: Option<usize>) -> usize {
        self.entries
            .iter()
            .enumerate()
            .filter(|(index, _)| Some(*index) != exclude)
            .map(|(_, entry)| {
                let blocks = match entry {
                    OutputEntry::Message(blocks) => blocks,
                    OutputEntry::Tool(tool) => &tool.media,
                };
                blocks
                    .iter()
                    .filter(|block| matches!(block, LensOutputBlock::Html { .. }))
                    .count()
            })
            .sum()
    }

    #[cfg(test)]
    pub(crate) fn from_blocks(blocks: Vec<LensOutputBlock>, received_updates: usize) -> Self {
        Self {
            entries: vec![OutputEntry::Message(blocks)],
            progress: ProgressText::default(),
            received_updates,
        }
    }
}

fn message_text_bytes(blocks: &[LensOutputBlock]) -> usize {
    blocks
        .iter()
        .map(|block| match block {
            LensOutputBlock::Markdown { text, .. } | LensOutputBlock::Html { text, .. } => {
                text.len()
            }
            _ => 0,
        })
        .sum()
}

fn encoded_image_bytes(blocks: &[LensOutputBlock]) -> usize {
    blocks
        .iter()
        .map(|block| match block {
            LensOutputBlock::Image { data, .. } => data.len(),
            _ => 0,
        })
        .sum()
}

fn push_output_block(blocks: &mut Vec<LensOutputBlock>, block: LensOutputBlock) {
    if let LensOutputBlock::Markdown { message_id, text } = &block {
        if text.is_empty() {
            return;
        }
        if let Some(LensOutputBlock::Markdown {
            message_id: previous_id,
            text: previous_text,
        }) = blocks.last_mut()
        {
            if previous_id == message_id {
                previous_text.push_str(text);
                return;
            }
        }
    }
    blocks.push(block);
}

fn lens_output_block(chunk: ContentChunk) -> LensOutputBlock {
    let message_id = chunk.message_id.map(|message_id| message_id.to_string());
    match chunk.content {
        ContentBlock::Text(content) => LensOutputBlock::Markdown {
            message_id,
            text: content.text,
        },
        ContentBlock::Image(content)
            if is_supported_image_mime_type(&content.mime_type)
                && is_valid_inline_image_data(&content.data) =>
        {
            LensOutputBlock::Image {
                message_id,
                mime_type: content.mime_type.to_ascii_lowercase(),
                data: content.data,
                uri: content.uri,
            }
        }
        ContentBlock::Image(content) => LensOutputBlock::Unsupported {
            message_id,
            content_type: format!("image ({})", content.mime_type),
        },
        ContentBlock::Audio(content) => LensOutputBlock::Unsupported {
            message_id,
            content_type: format!("audio ({})", content.mime_type),
        },
        ContentBlock::ResourceLink(_) => LensOutputBlock::Unsupported {
            message_id,
            content_type: "resource_link".into(),
        },
        ContentBlock::Resource(resource) => match resource.resource {
            EmbeddedResourceResource::TextResourceContents(content)
                if is_html_mime_type(content.mime_type.as_deref()) =>
            {
                if content.text.len() > MAX_HTML_BYTES {
                    LensOutputBlock::Unsupported {
                        message_id,
                        content_type: "html (size limit exceeded)".into(),
                    }
                } else {
                    LensOutputBlock::Html {
                        message_id,
                        resource_id: uuid::Uuid::new_v4().to_string(),
                        mime_type: "text/html".into(),
                        uri: content.uri,
                        byte_length: content.text.len(),
                        text: content.text,
                    }
                }
            }
            _ => LensOutputBlock::Unsupported {
                message_id,
                content_type: "resource".into(),
            },
        },
        _ => LensOutputBlock::Unsupported {
            message_id,
            content_type: "unknown".into(),
        },
    }
}

fn is_html_mime_type(mime_type: Option<&str>) -> bool {
    mime_type.is_some_and(|mime| {
        mime.split(';')
            .next()
            .is_some_and(|kind| kind.trim().eq_ignore_ascii_case("text/html"))
    })
}

fn is_tool_media(content: &ContentBlock) -> bool {
    match content {
        ContentBlock::Image(_) => true,
        ContentBlock::Resource(resource) => match &resource.resource {
            EmbeddedResourceResource::TextResourceContents(content) => {
                is_html_mime_type(content.mime_type.as_deref())
            }
            EmbeddedResourceResource::BlobResourceContents(content) => {
                is_html_mime_type(content.mime_type.as_deref())
            }
            _ => false,
        },
        _ => false,
    }
}

/// The retained count is supplied lazily because counting walks every entry and every one
/// of its blocks, while only an HTML block can exceed the per-turn limit. Message chunks
/// are overwhelmingly text and arrive once per ACP notification.
fn enforce_html_limit(block: &mut LensOutputBlock, retained: impl FnOnce() -> usize) {
    if let LensOutputBlock::Html { message_id, .. } = block {
        if retained() > 0 {
            *block = LensOutputBlock::Unsupported {
                message_id: message_id.clone(),
                content_type: "html (one resource per turn limit exceeded)".into(),
            };
        }
    }
}

pub(crate) fn is_supported_image_mime_type(mime_type: &str) -> bool {
    matches!(
        mime_type.to_ascii_lowercase().as_str(),
        "image/png" | "image/jpeg" | "image/gif" | "image/webp" | "image/avif"
    )
}

pub(crate) fn is_valid_inline_image_data(data: &str) -> bool {
    if data.is_empty() || data.len() > MAX_INLINE_IMAGE_ENCODED_BYTES {
        return false;
    }
    BASE64_STANDARD
        .decode(data)
        .is_ok_and(|decoded| decoded.len() <= MAX_INLINE_IMAGE_DECODED_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;
    use agent_client_protocol::schema::v1::{
        ImageContent, TextContent, ToolCall, ToolCallUpdate, ToolCallUpdateFields,
    };

    const SAFE_MODE: &str = "read-only";

    fn html_resource(value: &str, mime: &str) -> ContentBlock {
        use agent_client_protocol::schema::v1::{EmbeddedResource, TextResourceContents};
        ContentBlock::Resource(EmbeddedResource::new(
            EmbeddedResourceResource::TextResourceContents(
                TextResourceContents::new(value, "urn:test:html").mime_type(mime),
            ),
        ))
    }

    #[test]
    fn direct_publication_preserves_private_body_and_receipt_identity() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(text("Summary", "result"), SAFE_MODE)
            .unwrap();
        let id = uuid::Uuid::new_v4();
        let html = "<p>\u{65e5}\u{672c}\u{8a9e}\u{306e}\u{7d50}\u{679c}</p>";
        candidate
            .accept_published_html(adapter_output_mcp::PublishedHtml {
                id,
                html: html.into(),
            })
            .unwrap();
        let blocks = candidate.blocks();
        assert!(matches!(&blocks[0], LensOutputBlock::Markdown { text, .. } if text == "Summary"));
        assert!(matches!(&blocks[1], LensOutputBlock::Html {
            resource_id, text, byte_length, ..
        } if resource_id == &id.to_string() && text == html && *byte_length == html.len()));
        assert!(candidate.has_output());
        let snapshot = serde_json::to_value(&blocks).unwrap();
        assert!(snapshot[1].get("text").is_none());
        assert!(!snapshot.to_string().contains(html));
        assert!(candidate
            .accept_published_html(adapter_output_mcp::PublishedHtml {
                id: uuid::Uuid::new_v4(),
                html: "<p>second</p>".into(),
            })
            .is_err());
        assert_eq!(candidate.blocks(), blocks);
    }

    #[test]
    fn direct_publication_rejects_invalid_body_and_existing_acp_html() {
        for html in [" ".into(), "x".repeat(MAX_HTML_BYTES + 1)] {
            let mut candidate = AgentOutputCandidate::default();
            assert!(candidate
                .accept_published_html(adapter_output_mcp::PublishedHtml {
                    id: uuid::Uuid::new_v4(),
                    html,
                })
                .is_err());
            assert!(!candidate.has_output());
        }
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                SessionUpdate::AgentMessageChunk(ContentChunk::new(html_resource(
                    "<p>upstream</p>",
                    "text/html",
                ))),
                SAFE_MODE,
            )
            .unwrap();
        assert!(candidate
            .accept_published_html(adapter_output_mcp::PublishedHtml {
                id: uuid::Uuid::new_v4(),
                html: "<p>direct</p>".into(),
            })
            .is_err());
        assert_eq!(candidate.blocks().len(), 1);
    }

    #[test]
    fn html_is_bounded_private_and_counts_as_output() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                SessionUpdate::AgentMessageChunk(ContentChunk::new(html_resource(
                    "<p>\u{65e5}\u{672c}\u{8a9e}</p>",
                    " Text/HTML; charset=utf-8",
                ))),
                SAFE_MODE,
            )
            .unwrap();
        assert!(candidate.has_output());
        let blocks = candidate.blocks();
        let LensOutputBlock::Html {
            text: private_text,
            byte_length,
            mime_type,
            resource_id,
            ..
        } = &blocks[0]
        else {
            panic!("expected HTML")
        };
        assert_eq!(*byte_length, private_text.len());
        assert_eq!(mime_type, "text/html");
        assert!(uuid::Uuid::parse_str(resource_id).is_ok());
        let public = serde_json::to_value(&blocks).unwrap();
        assert!(public[0].get("text").is_none());
        assert!(!public.to_string().contains("\u{65e5}\u{672c}\u{8a9e}"));
        candidate
            .record_update(
                SessionUpdate::AgentMessageChunk(ContentChunk::new(html_resource(
                    "second",
                    "text/html",
                ))),
                SAFE_MODE,
            )
            .unwrap();
        assert!(matches!(
            candidate.blocks()[1],
            LensOutputBlock::Unsupported { .. }
        ));
        candidate
            .record_update(text("ordinary result", "message-2"), SAFE_MODE)
            .unwrap();
        assert!(matches!(
            candidate.blocks().last(),
            Some(LensOutputBlock::Markdown { .. })
        ));
        for resource in [
            html_resource(&"x".repeat(MAX_HTML_BYTES + 1), "text/html"),
            html_resource("x", "text/plain"),
        ] {
            assert!(matches!(
                lens_output_block(ContentChunk::new(resource)),
                LensOutputBlock::Unsupported { .. }
            ));
        }
        assert!(matches!(
            lens_output_block(ContentChunk::new(html_resource(
                &"x".repeat(MAX_HTML_BYTES),
                "text/html"
            ))),
            LensOutputBlock::Html { .. }
        ));
    }

    #[test]
    fn blob_html_is_not_decoded_or_rendered() {
        use agent_client_protocol::schema::v1::{BlobResourceContents, EmbeddedResource};
        let resource = ContentBlock::Resource(EmbeddedResource::new(
            EmbeddedResourceResource::BlobResourceContents(
                BlobResourceContents::new("PGgxPkhlbGxvPC9oMT4=", "urn:blob")
                    .mime_type("text/html"),
            ),
        ));
        assert!(matches!(
            lens_output_block(ContentChunk::new(resource)),
            LensOutputBlock::Unsupported { .. }
        ));
    }

    #[test]
    fn failed_tools_release_the_html_slot_for_the_agent_result() {
        for initial_status in [ToolCallStatus::InProgress, ToolCallStatus::Failed] {
            let mut candidate = AgentOutputCandidate::default();
            candidate
                .update_tool(
                    "failed-html".into(),
                    Some(initial_status),
                    Some(vec![html_resource("<p>partial</p>", "text/html").into()]),
                )
                .unwrap();
            candidate
                .update_tool("failed-html".into(), Some(ToolCallStatus::Failed), None)
                .unwrap();
            assert_eq!(candidate.retained_html_count(None), 0);
            candidate
                .record_update(
                    SessionUpdate::AgentMessageChunk(ContentChunk::new(html_resource(
                        "<p>final</p>",
                        "text/html",
                    ))),
                    SAFE_MODE,
                )
                .unwrap();
            assert!(matches!(
                candidate.blocks().as_slice(),
                [LensOutputBlock::Html { .. }]
            ));
        }
    }

    #[test]
    fn non_html_tool_resources_remain_private_and_do_not_count_as_output() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .update_tool(
                "resource-tool".into(),
                Some(ToolCallStatus::Completed),
                Some(vec![
                    html_resource("private resource", "text/plain").into(),
                    html_resource("{\"private\":true}", "application/json").into(),
                ]),
            )
            .unwrap();
        assert!(candidate.blocks().is_empty());
        assert!(!candidate.has_output());
        candidate
            .update_tool(
                "resource-tool".into(),
                None,
                Some(vec![html_resource(
                    "<p>result</p>",
                    "Text/HTML; charset=utf-8",
                )
                .into()]),
            )
            .unwrap();
        assert!(candidate.has_output());
        assert!(matches!(
            candidate.blocks()[0],
            LensOutputBlock::Html { .. }
        ));
    }

    #[test]
    fn html_tool_snapshots_are_only_visible_when_completed_and_replace() {
        let mut candidate = AgentOutputCandidate::default();
        let content = || vec![html_resource("<p>tool</p>", "text/html").into()];
        candidate
            .update_tool(
                "html-tool".into(),
                Some(ToolCallStatus::InProgress),
                Some(content()),
            )
            .unwrap();
        assert!(!candidate.has_output());
        candidate
            .update_tool("html-tool".into(), Some(ToolCallStatus::Completed), None)
            .unwrap();
        assert!(matches!(
            candidate.blocks()[0],
            LensOutputBlock::Html { .. }
        ));
        assert!(!candidate
            .update_tool("html-tool".into(), None, Some(content()))
            .unwrap());
        assert!(matches!(
            candidate.blocks()[0],
            LensOutputBlock::Html { .. }
        ));
        candidate
            .update_tool("html-tool".into(), None, Some(vec![]))
            .unwrap();
        assert!(!candidate.has_output());
    }

    #[test]
    fn public_progress_accumulates_deltas_without_becoming_interpretation() {
        let mut candidate = AgentOutputCandidate::default();
        for value in ["Comparing ", "the sources.\n", "Checking changes"] {
            let update = SessionUpdate::AgentThoughtChunk(
                ContentChunk::new(ContentBlock::Text(TextContent::new(value)))
                    .message_id("thought-1"),
            );
            assert!(!candidate.record_update(update, SAFE_MODE).unwrap());
        }
        assert_eq!(
            candidate.progress_text().as_deref(),
            Some("Checking changes")
        );
        assert!(candidate.blocks().is_empty());
        assert!(!candidate.has_output());
        candidate
            .record_update(text("Result", "message-1"), SAFE_MODE)
            .unwrap();
        assert_eq!(candidate.progress_text().as_deref(), Some("Result"));
        assert_eq!(candidate.blocks().len(), 1);
    }

    #[test]
    fn progress_is_unicode_bounded_and_resets_at_message_and_turn_boundaries() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(text(&"\u{754c}".repeat(1000), "first"), SAFE_MODE)
            .unwrap();
        assert_eq!(candidate.progress_text().unwrap(), "\u{754c}".repeat(512));
        candidate
            .record_update(text("New message", "second"), SAFE_MODE)
            .unwrap();
        assert_eq!(candidate.progress_text().as_deref(), Some("New message"));
        assert!(AgentOutputCandidate::default().progress_text().is_none());
    }

    fn image(data: &str) -> ToolCallContent {
        ContentBlock::Image(
            ImageContent::new(data, "image/png").uri("file:///unread/generated.png"),
        )
        .into()
    }

    fn text(text: &str, message: &str) -> SessionUpdate {
        SessionUpdate::AgentMessageChunk(
            ContentChunk::new(ContentBlock::Text(TextContent::new(text))).message_id(message),
        )
    }

    fn update(id: &str, fields: ToolCallUpdateFields) -> SessionUpdate {
        SessionUpdate::ToolCallUpdate(ToolCallUpdate::new(id.to_owned(), fields))
    }

    fn completed(id: &str, content: Vec<ToolCallContent>) -> SessionUpdate {
        SessionUpdate::ToolCall(
            ToolCall::new(id.to_owned(), "Image generation")
                .status(ToolCallStatus::Completed)
                .content(content),
        )
    }

    fn image_data(candidate: &AgentOutputCandidate) -> Vec<String> {
        candidate
            .blocks()
            .into_iter()
            .filter_map(|block| match block {
                LensOutputBlock::Image { data, .. } => Some(data),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn completed_tool_snapshot_renders_images_without_exposing_tool_prose() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                completed(
                    "image-1",
                    vec![
                        ContentBlock::Text(TextContent::new("Revised prompt: private tool detail"))
                            .into(),
                        image("aW1hZ2U="),
                        image("c2Vjb25k"),
                    ],
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert!(candidate.has_output());
        assert_eq!(image_data(&candidate), ["aW1hZ2U=", "c2Vjb25k"]);
        assert_eq!(candidate.blocks().len(), 2);
        assert!(matches!(&candidate.blocks()[0], LensOutputBlock::Image {
            message_id: None, uri: Some(uri), ..
        } if uri == "file:///unread/generated.png"));
    }

    #[test]
    fn status_only_completion_publishes_retained_images_at_the_tool_position() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(text("Before", "before"), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(
                SessionUpdate::ToolCall(
                    ToolCall::new("image-1", "Generating")
                        .status(ToolCallStatus::InProgress)
                        .content(vec![image("aW1hZ2U=")]),
                ),
                SAFE_MODE,
            )
            .unwrap();
        candidate
            .record_update(text("After", "after"), SAFE_MODE)
            .unwrap();
        assert!(image_data(&candidate).is_empty());
        assert!(candidate
            .record_update(
                update(
                    "image-1",
                    ToolCallUpdateFields::new().status(ToolCallStatus::Completed)
                ),
                SAFE_MODE
            )
            .unwrap());
        assert!(matches!(candidate.blocks().as_slice(), [
            LensOutputBlock::Markdown { text: before, .. },
            LensOutputBlock::Image { .. },
            LensOutputBlock::Markdown { text: after, .. }
        ] if before == "Before" && after == "After"));
    }

    #[test]
    fn completed_update_without_start_and_repeated_updates_do_not_duplicate_images() {
        let mut candidate = AgentOutputCandidate::default();
        let event = update(
            "image-1",
            ToolCallUpdateFields::new()
                .status(ToolCallStatus::Completed)
                .content(vec![image("aW1hZ2U=")]),
        );
        assert!(candidate.record_update(event.clone(), SAFE_MODE).unwrap());
        candidate
            .record_update(text("After", "after"), SAFE_MODE)
            .unwrap();
        assert!(!candidate.record_update(event, SAFE_MODE).unwrap());
        assert!(!candidate
            .record_update(
                update(
                    "image-1",
                    ToolCallUpdateFields::new().title("Metadata only")
                ),
                SAFE_MODE
            )
            .unwrap());
        assert_eq!(image_data(&candidate), ["aW1hZ2U="]);
        assert_eq!(candidate.received_updates, 4);
    }

    #[test]
    fn content_replaces_instead_of_appending_and_empty_content_clears() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                completed("image-1", vec![image("Zmlyc3Q="), image("c2Vjb25k")]),
                SAFE_MODE,
            )
            .unwrap();
        candidate
            .record_update(text("After", "after"), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(
                update(
                    "image-1",
                    ToolCallUpdateFields::new().content(vec![image("cmVwbGFjZWQ=")]),
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert_eq!(image_data(&candidate), ["cmVwbGFjZWQ="]);
        assert!(matches!(
            candidate.blocks()[0],
            LensOutputBlock::Image { .. }
        ));
        candidate
            .record_update(
                update("image-1", ToolCallUpdateFields::new().content(vec![])),
                SAFE_MODE,
            )
            .unwrap();
        assert!(image_data(&candidate).is_empty());
        assert_eq!(candidate.blocks().len(), 1);
    }

    #[test]
    fn interleaved_tools_keep_creation_order_and_failed_tools_have_no_visible_media() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                SessionUpdate::ToolCall(ToolCall::new("first", "First")),
                SAFE_MODE,
            )
            .unwrap();
        candidate
            .record_update(completed("second", vec![image("c2Vjb25k")]), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(
                update(
                    "first",
                    ToolCallUpdateFields::new()
                        .status(ToolCallStatus::Completed)
                        .content(vec![image("Zmlyc3Q=")]),
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert_eq!(image_data(&candidate), ["Zmlyc3Q=", "c2Vjb25k"]);
        candidate
            .record_update(
                update(
                    "first",
                    ToolCallUpdateFields::new().status(ToolCallStatus::Failed),
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert_eq!(image_data(&candidate), ["c2Vjb25k"]);
        let mut next_turn = AgentOutputCandidate::default();
        next_turn
            .record_update(
                update(
                    "first",
                    ToolCallUpdateFields::new().status(ToolCallStatus::Completed),
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert!(!next_turn.has_output());
    }

    #[test]
    fn pending_failed_or_unknown_status_never_publishes_an_image() {
        for status in [
            ToolCallStatus::Pending,
            ToolCallStatus::InProgress,
            ToolCallStatus::Failed,
        ] {
            let mut candidate = AgentOutputCandidate::default();
            candidate
                .record_update(
                    update(
                        "image-1",
                        ToolCallUpdateFields::new()
                            .status(status)
                            .content(vec![image("aW1hZ2U=")]),
                    ),
                    SAFE_MODE,
                )
                .unwrap();
            assert!(!candidate.has_output());
            assert!(candidate.blocks().is_empty());
        }
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(
                update(
                    "image-1",
                    ToolCallUpdateFields::new().content(vec![image("aW1hZ2U=")]),
                ),
                SAFE_MODE,
            )
            .unwrap();
        assert!(!candidate.has_output());
    }

    #[test]
    fn tool_images_share_message_image_validation_and_other_content_stays_private() {
        let update: SessionUpdate = serde_json::from_value(serde_json::json!({
            "sessionUpdate": "tool_call", "toolCallId": "mixed", "title": "Mixed", "status": "completed",
            "rawOutput": { "data": "aW1hZ2U=", "mimeType": "image/png" },
            "content": [
                {"type":"content", "content":{"type":"image", "mimeType":"image/png", "data":"invalid!"}},
                {"type":"content", "content":{"type":"image", "mimeType":"image/svg+xml", "data":"PHN2Zz4="}},
                {"type":"content", "content":{"type":"text", "text":"![tool prose](file:///private.png)"}},
                {"type":"content", "content":{"type":"resource_link", "name":"private", "uri":"file:///private.png"}},
                {"type":"diff", "path":"/private/file", "oldText":null, "newText":"private"},
                {"type":"terminal", "terminalId":"private-terminal"}
            ]
        })).unwrap();
        let mut candidate = AgentOutputCandidate::default();
        candidate.record_update(update, SAFE_MODE).unwrap();
        assert_eq!(candidate.blocks().len(), 2);
        assert!(candidate
            .blocks()
            .iter()
            .all(|block| matches!(block, LensOutputBlock::Unsupported { .. })));
    }

    #[test]
    fn markdown_merges_only_adjacent_content_from_the_same_message() {
        let mut candidate = AgentOutputCandidate::default();
        candidate
            .record_update(text("First ", "same"), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(
                completed(
                    "text-tool",
                    vec![ContentBlock::Text(TextContent::new("Hidden")).into()],
                ),
                SAFE_MODE,
            )
            .unwrap();
        candidate
            .record_update(text("message", "same"), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(completed("image", vec![image("aW1hZ2U=")]), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(text("After", "same"), SAFE_MODE)
            .unwrap();
        candidate
            .record_update(text("Next", "next"), SAFE_MODE)
            .unwrap();
        assert!(matches!(candidate.blocks().as_slice(), [
            LensOutputBlock::Markdown { text: first, .. }, LensOutputBlock::Image { .. },
            LensOutputBlock::Markdown { text: after, .. }, LensOutputBlock::Markdown { text: next, .. }
        ] if first == "First message" && after == "After" && next == "Next"));
    }

    #[test]
    fn tool_state_is_bounded_and_replacement_does_not_consume_another_slot() {
        let mut candidate = AgentOutputCandidate::default();
        for index in 0..MAX_TOOL_CALLS {
            candidate
                .record_update(completed(&index.to_string(), vec![]), SAFE_MODE)
                .unwrap();
        }
        candidate
            .record_update(completed("0", vec![image("aW1hZ2U=")]), SAFE_MODE)
            .unwrap();
        assert!(candidate
            .record_update(completed("overflow", vec![]), SAFE_MODE)
            .is_err());
        assert_eq!(image_data(&candidate), ["aW1hZ2U="]);
        assert!(candidate
            .record_update(
                completed("0", vec![image("aW1hZ2U="); MAX_TOOL_MEDIA_BLOCKS + 1]),
                SAFE_MODE
            )
            .is_err());
        assert_eq!(image_data(&candidate), ["aW1hZ2U="]);
    }

    #[test]
    fn retained_image_bytes_are_bounded_even_before_tool_completion() {
        let mut candidate = AgentOutputCandidate::default();
        let data = BASE64_STANDARD.encode(vec![0_u8; MAX_INLINE_IMAGE_DECODED_BYTES]);
        for index in 0..4 {
            candidate
                .record_update(
                    update(
                        &index.to_string(),
                        ToolCallUpdateFields::new().content(vec![image(&data)]),
                    ),
                    SAFE_MODE,
                )
                .unwrap();
        }
        assert!(candidate
            .record_update(
                update(
                    "overflow",
                    ToolCallUpdateFields::new().content(vec![image(&data)])
                ),
                SAFE_MODE
            )
            .is_err());
        assert!(!candidate.has_output());
        candidate
            .record_update(
                update("0", ToolCallUpdateFields::new().content(vec![])),
                SAFE_MODE,
            )
            .unwrap();
        candidate
            .record_update(completed("replacement", vec![image(&data)]), SAFE_MODE)
            .unwrap();
        assert_eq!(image_data(&candidate).len(), 1);
    }

    #[test]
    fn safe_mode_changes_still_fail_closed() {
        let mut candidate = AgentOutputCandidate::default();
        let event: SessionUpdate = serde_json::from_value(serde_json::json!({
            "sessionUpdate":"current_mode_update", "currentModeId":"full-access"
        }))
        .unwrap();
        assert!(candidate.record_update(event, SAFE_MODE).is_err());
    }

    #[test]
    fn whitespace_only_markdown_is_not_displayable_output() {
        let mut candidate = AgentOutputCandidate::default();
        assert!(!candidate
            .record_update(text("", "same"), SAFE_MODE)
            .unwrap());
        candidate
            .record_update(text(" \n\t", "same"), SAFE_MODE)
            .unwrap();
        assert!(!candidate.has_output());
        candidate
            .record_update(completed("image", vec![image("invalid!")]), SAFE_MODE)
            .unwrap();
        assert!(candidate.has_output());
    }

    #[test]
    fn acp_text_and_image_chunks_become_typed_output_blocks() {
        let text = lens_output_block(
            ContentChunk::new(ContentBlock::Text(TextContent::new("Description")))
                .message_id("message-1"),
        );
        let image = lens_output_block(
            ContentChunk::new(ContentBlock::Image(
                ImageContent::new("iVBORw0KGgo=", "IMAGE/PNG").uri("urn:fixture:image"),
            ))
            .message_id("message-1"),
        );

        assert_eq!(
            text,
            LensOutputBlock::Markdown {
                message_id: Some("message-1".into()),
                text: "Description".into(),
            }
        );
        assert_eq!(
            image,
            LensOutputBlock::Image {
                message_id: Some("message-1".into()),
                mime_type: "image/png".into(),
                data: "iVBORw0KGgo=".into(),
                uri: Some("urn:fixture:image".into()),
            }
        );
    }

    #[test]
    fn image_output_uses_an_explicit_finite_mime_type_allowlist() {
        for mime_type in [
            "image/png",
            "image/jpeg",
            "image/gif",
            "image/webp",
            "image/avif",
        ] {
            assert!(is_supported_image_mime_type(mime_type));
        }
        assert!(!is_supported_image_mime_type("image/svg+xml"));

        let unsupported = lens_output_block(ContentChunk::new(ContentBlock::Image(
            ImageContent::new("PHN2Zz4=", "image/svg+xml"),
        )));
        assert_eq!(
            unsupported,
            LensOutputBlock::Unsupported {
                message_id: None,
                content_type: "image (image/svg+xml)".into(),
            }
        );

        let invalid_data = lens_output_block(ContentChunk::new(ContentBlock::Image(
            ImageContent::new("not base64", "image/png"),
        )));
        assert_eq!(
            invalid_data,
            LensOutputBlock::Unsupported {
                message_id: None,
                content_type: "image (image/png)".into(),
            }
        );
    }

    #[test]
    fn image_output_rejects_encoded_and_decoded_payloads_above_the_inline_limit() {
        let oversized_encoded = "A".repeat(MAX_INLINE_IMAGE_ENCODED_BYTES + 1);
        assert!(!is_valid_inline_image_data(&oversized_encoded));

        let oversized_decoded =
            BASE64_STANDARD.encode(vec![0_u8; MAX_INLINE_IMAGE_DECODED_BYTES + 1]);
        assert_eq!(oversized_decoded.len(), MAX_INLINE_IMAGE_ENCODED_BYTES);
        assert!(!is_valid_inline_image_data(&oversized_decoded));

        let unsupported = lens_output_block(ContentChunk::new(ContentBlock::Image(
            ImageContent::new(oversized_encoded, "image/png"),
        )));
        assert_eq!(
            unsupported,
            LensOutputBlock::Unsupported {
                message_id: None,
                content_type: "image (image/png)".into(),
            }
        );
    }
}
